pipeline {
    agent any

    environment {
        // We will configure these secrets in Jenkins later
        GHCR_CREDENTIALS_ID = 'ghcr-login'
        IMAGE_NAME = 'ghcr.io/vedantkhursange/orangy-backend'
    }

    stages {
        stage('Build & Push Docker Image') {
            steps {
                script {
                    // Navigate into the backend folder before building
                    dir('orangy-backend') {
                        withCredentials([usernamePassword(credentialsId: GHCR_CREDENTIALS_ID, passwordVariable: 'GHCR_PASS', usernameVariable: 'GHCR_USER')]) {
                            sh 'echo "$GHCR_PASS" | docker login ghcr.io -u "$GHCR_USER" --password-stdin'
                            sh "docker build -t ${IMAGE_NAME}:dev-latest ."
                            sh "docker push ${IMAGE_NAME}:dev-latest"
                        }
                    }
                }
            }
        }

        stage('Deploy (Trigger ArgoCD)') {
            steps {
                script {
                    // Since ArgoCD monitors our manifests, pushing the image to GHCR is enough.
                    // However, we can run a kubectl command to force a restart to pull the new image immediately.
                    sh 'kubectl rollout restart deployment backend -n orangy-dev'
                }
            }
        }
    }
}
